### ISSUE TITLE
need a help

### ISSUE THREAD

**Issue by davoodfattah** [crazyhottommy/RNA-seq-analysis#12]
Hello Sir, how can I start to analyze rna_seq data as a beginner? I have seen many videos on youtube but ... .
I am confused deeply. I hope you to aid me.

Sincerely

**Comment by crazyhottommy** [comment]
Hi, can you please be specific about what you want? take a look at https://tavareshugo.github.io/data-carpentry-rnaseq/ too

**Comment by davoodfattah** [comment]
Hi Sir
In fact, I have to learn how to analyze data of rna_seq for my thesis. I
watched countless videos on youtube and asked to help different people
but...
So, I know about NGS completely but I WANT  to learn deeply. It is about y
major. I tried to learn many times. Actually, I am confused. I do not know
how to start. Although I know something in this way. In the end, I ask you
to guide me and push me and shake my hand. I am waiting for your kind
response.
