### ISSUE TITLE
Link to lfcThreshold code

### ISSUE THREAD

**Issue by mikelove** [crazyhottommy/RNA-seq-analysis#8]
For the "genes not DE" markdown, some users are getting confused by the code from a 2013 support site post from Simon. Around 2014 we implemented lfcThreshold as an argument of results() which takes care of everything for the user. Could you point users to this section of the vignette for the "not DE" analysis?

https://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#tests-of-log2-fold-change-above-or-below-a-threshold

**Comment by crazyhottommy** [comment]
@mikelove Thank you Mike. I just updated the markdown and linked to the section.
