### ISSUE TITLE
How to understand meanFragmentLength when calculate TPM?

### ISSUE THREAD

**Issue by ShixiangWang** [crazyhottommy/RNA-seq-analysis#9]
Dear @crazyhottommy,

Thanks for your [nice blog](https://github.com/crazyhottommy/RNA-seq-analysis/blob/master/salmon_kalliso_STAR_compare.md), I have trouble with understanding the concept of `meanFragmentLength`. 

You use the following code for your data

```
## fragment length is 200bp 
meanFragmentLength<- c(200, 200, 200)
```

Does this mean your data is pair-end with 100bp read length? And the formula based on effective length seems different from the original formula, is this a promotion version?

Best,
Shixiang

**Comment by crazyhottommy** [comment]
Hi Shixiang,

please read http://thegenomefactory.blogspot.com/2013/08/paired-end-read-confusion-library.html
Usually, mean fragment length can be inferred from the data. in this example, I use 200bp as roughly this is the fragment size in the library.

**Comment by ShixiangWang** [comment]
@crazyhottommy Got it, thanks.
